version: "3.7"

services:
  api:
    image: ys2lee/stable-diffusion-api:${TAG:-latest}
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: unless-stopped
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - /home/{USERNAME}/.cache/huggingface:/root/.cache/huggingface
      - ./static:/app/static
    environment:
      MODEL_ID: "runwayml/stable-diffusion-v1-5"
      MB_BATCH_SIZE: 1

      CUDA_DEVICE: cuda
      HUGGINGFACE_TOKEN: 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
      IMAGESERVER_URL: http://44.192.70.46:3000/images
      MB_TIMEOUT: 200
      SAVE_DIR: static

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  frontend:
    depends_on:
      - api

    image: ys2lee/stable-diffusion-streamlit:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile

    restart: unless-stopped
    ports:
      - 8501:8501
    expose:
      - 8501
    environment:
      TZ: Asia/Seoul
      API_URL: http://44.192.70.46:3000
      ST_TITLE: Stable-diffusion
      ST_WIDE: "True"
